spring:
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/Imker
    username: postgres
    password: root
  jpa:
    hibernate:
      ddl-auto: none
      format_sql: true
      use_sql_comments: true
    show-sql: true
  mvc:
    cors:
      allowed-origins: http://localhost:5173

logging:
  level:
    org:
      springframework:
        security: TRACE
users:
  sort:
    fields: name,plz,role,state,id
  filter:
    fields: role,state
  page:
    size: 3

events:
  sort:
    fields: dateStart
  filter:
    fields: dateStart
  page:
    size: 3

