spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/Imker
    username: postgres
    password: root

    hikari:
      connectionTimeout: 20000
      minimumIdle: 10
      maximumPoolSize: 20
      idleTimeout: 300000
      maxLifetime: 1800000

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate.format_sql: true
      hibernate.use_sql_comments: true

  mvc:
    cors:
      allowed-origins: http://localhost:5173


# DigitalOcean Spaces settings
aws:
  accessKeyId: DO00H2QQZY9Y389QVZKL
  secretKey: QkPN3Lc61q5vXJOM+jxjz3IVHXgK6OVxBw1W371p65s
  s3:
    bucketName: imker
    endpointUrl: fra1.digitaloceanspaces.com


#logging:
#  level:
#    org:
#      springframework:
#        security: TRACE

users:
  sort:
    fields: name,plz,role,state,id
  filter:
    fields: role,state
  page:
    size: 3

events:
  sort:
    fields: dateStart
  filter:
    fields: dateStart

files:
  upload:
    path: uploads/

