
### Add event №1

POST http://localhost:8080/api/events
Content-Type: application/json

{
  "title": "Wine festival",
  "description": "Many local winemakers",
  "shortDescription": "Wine with love",
  "address": "Berlin, Winehof, 8",
  "author": "Andrii",
  "quantityOfMembers": "25",
  "location": "<iframe src=\"https://www.google.com/maps/embed?pb=!1m14!1m8!1m3!1d2430.1166171018426!2d13.2207348!3d52.4770242!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x47a859bdeafe589f%3A0xa79c987b6c7854a3!2z0KTQvtGA0YHRgiDQk9GA0YPQvdC10LLQsNC70YzQtA!5e0!3m2!1sru!2sde!4v1692992412612!5m2!1sru!2sde\" width=\"600\" height=\"450\" style=\"border:0;\" allowfullscreen=\"\" loading=\"lazy\" referrerpolicy=\"no-referrer-when-downgrade\"></iframe>",
  "photo": "C://Photos/added_photo.png",
  "startTime": "12:00",
  "endTime": "18:00",
  "dateStart": "2023-10-01",
  "dateEnd": "2023-10-03"
}

### Add event №2

POST http://localhost:8080/api/events
Content-Type: application/json


{
  "title": "Circus",
  "description": "Kids circus",
  "shortDescription": "Kids with tigers",
  "address": "Bremen, CircusHof, 11",
  "author": "Andrii",
  "quantityOfMembers": "250",
  "location": "<iframe src=\"https://www.google.com/maps/embed?pb=!1m14!1m8!1m3!1d2430.1166171018426!2d13.2207348!3d52.4770242!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x47a859bdeafe589f%3A0xa79c987b6c7854a3!2z0KTQvtGA0YHRgiDQk9GA0YPQvdC10LLQsNC70YzQtA!5e0!3m2!1sru!2sde!4v1692992412612!5m2!1sru!2sde\" width=\"600\" height=\"450\" style=\"border:0;\" allowfullscreen=\"\" loading=\"lazy\" referrerpolicy=\"no-referrer-when-downgrade\"></iframe>",
  "photo": "C://Photos/added photo #2png",
  "startTime": "09:00",
  "endTime": "12:00",
  "dateStart": "2023-10-02",
  "dateEnd": "2023-10-04"
}




### Add event №3

POST http://localhost:8080/api/events
Content-Type: application/json

{
  "title": "Karaoke",
  "description": "Singing Song",
  "shortDescription": "Main guest - Sting",
  "address": "msterdam, Sing allee, 5",
  "author": "Joseph",
  "quantityOfMembers": "12",
  "location": "<iframe src=\"https://www.google.com/maps/embed?pb=!1m14!1m8!1m3!1d2430.1166171018426!2d13.2207348!3d52.4770242!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x47a859bdeafe589f%3A0xa79c987b6c7854a3!2z0KTQvtGA0YHRgiDQk9GA0YPQvdC10LLQsNC70YzQtA!5e0!3m2!1sru!2sde!4v1692992412612!5m2!1sru!2sde\" width=\"600\" height=\"450\" style=\"border:0;\" allowfullscreen=\"\" loading=\"lazy\" referrerpolicy=\"no-referrer-when-downgrade\"></iframe>",
  "photo": "C://Photos/added_photo_сфкфщлу.png",
  "startTime": "19:00",
  "endTime": "23:00",
  "dateStart": "2023-11-01",
  "dateEnd": "2023-11-03"
}


### Add event №4

POST http://localhost:8080/api/events
Content-Type: application/json

{
  "title": "Exciting Adventure Meetup",
  "description": "Join us for an exhilarating day of outdoor adventures and camaraderie!",
  "shortDescription": "You can try new sorts of Honig",
  "address": "123 Adventure Street, Summitville",
  "author": "Adventure Enthusiast Club",
  "quantityOfMembers": "25",
  "location": "<iframe src=\"https://www.google.com/maps/embed?pb=!1m14!1m8!1m3!1d2430.1166171018426!2d13.2207348!3d52.4770242!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x47a859bdeafe589f%3A0xa79c987b6c7854a3!2z0KTQvtGA0YHRgiDQk9GA0YPQvdC10LLQsNC70YzQtA!5e0!3m2!1sru!2sde!4v1692992412612!5m2!1sru!2sde\" width=\"600\" height=\"450\" style=\"border:0;\" allowfullscreen=\"\" loading=\"lazy\" referrerpolicy=\"no-referrer-when-downgrade\"></iframe>",
  "photo": "https://example.com/event-photo.jpg",
  "startTime": "10:00",
  "endTime": "4:00 ",
  "dateStart": "2023-12-01",
  "dateEnd": "2023-12-03"
}

### Add event №5

POST http://localhost:8080/api/events
Content-Type: application/json

{
  "title": "Gourmet Delights Cooking Class",
  "description": "Embark on a culinary journey as our experienced chefs guide you through the art of gourmet cooking.",
  "shortDescription": "Baking with honig",
  "address": "456 Culinary Lane, Savoryville",
  "author": "TasteBuds Culinary School",
  "quantityOfMembers": "15",
  "location": "<iframe src=\"https://www.google.com/maps/embed?pb=!1m14!1m8!1m3!1d2430.1166171018426!2d13.2207348!3d52.4770242!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x47a859bdeafe589f%3A0xa79c987b6c7854a3!2z0KTQvtGA0YHRgiDQk9GA0YPQvdC10LLQsNC70YzQtA!5e0!3m2!1sru!2sde!4v1692992412612!5m2!1sru!2sde\" width=\"600\" height=\"450\" style=\"border:0;\" allowfullscreen=\"\" loading=\"lazy\" referrerpolicy=\"no-referrer-when-downgrade\"></iframe>",
  "photo": "https://example.com/cooking-class.jpg",
  "startTime": "6:30",
  "endTime": "9:00",
  "dateStart": "2023-09-01",
  "dateEnd": "2023-09-03"
}


### Get all events
GET localhost:8080/api/events



### Get Event (sort)order by description - works
GET localhost:8080/api/events?orderBy=description&desc=false&page=0


### Get Event (sort)order by description - works DESC
GET localhost:8080/api/events?orderBy=description&desc=true&page=0


### Get Event (sort)order by Title WORKS
GET localhost:8080/api/events?orderBy=title&desc=false&page=1


### Get Event (sort)order by startTime WORKS
GET localhost:8080/api/events?orderBy=startTime&desc=false&page=0


### Get Event (sort)order by endDate WORKS
GET localhost:8080/api/events?orderBy=endTime&desc=false&page=0


### Get Event (sort) by startTime And Filtred BY Finish date
GET localhost:8080/api/events?orderBy=startTime&desc=true&page=0&filterBy=date&filterValue=2023-01-12

### GET Event

GET localhost:8080/api/events/4



### Delete Event WORKS

DELETE localhost:8080/api/events/2

### Update event

PUT localhost:8080/api/events/2
Content-Type: application/json

{
  "title" : "Second",
  "status" : "ENDED",
  "address" : "",
  "author" : "updatedNewAuthor",
  "description" : "updatedNewDescription",
  "shortDescription" : "somethingShort",
  "location" : "updatedNewLocation",
  "photo" : "updatedNewPhotoAddress",
  "dateStart" : "2024-04-04",
  "dateEnd" : "2024-04-05",
  "startTime" : "12:12",
  "endTime" : "13:13"

}


### Get Event (sort)order by startDAte WORKS
GET localhost:8080/api/events?orderBy=dateStart&desc=false&pageSize=3&page=0




