### Создание события №1

POST http://localhost:8080/api/events
Content-Type: application/json

{
  "name": "Wine festival",
  "description": "Many local winemakers",
  "author": "Andrii",
  "place": "Berlin, Winehof, 8",
  "quantityOfMembers": "25",
  "photo": "added photo",
  "date": "01/08/2023"

}

### Создание события №2

POST http://localhost:8080/api/events
Content-Type: application/json

{
  "name": "Circus",
  "description": "Kids circus",
  "author": "Andrii",
  "place": "Bremen, CircusHof, 11",
  "quantityOfMembers": "250",
  "photo": "added photo #2",
  "date": "01/09/2023"

}



### Получение всех событий

GET localhost:8080/api/events


### Удаление события

DELETE localhost:8080/api/events/1

### Обновление события №1

PUT localhost:8080/api/events/2
Content-Type: application/json

{
  "newStatus" : "ENDED"
}
