
### Add event №1

POST http://localhost:8080/api/events
Content-Type: application/json

{
  "title": "Wine festival",
  "description": "Many local winemakers",
  "address": "Berlin, Winehof, 8",
  "author": "Andrii",
  "quantityOfMembers": "25",
  "photo": "C://Photos/added_photo.png",
  "date": "2023-02-02"

}

### Add event №2

POST http://localhost:8080/api/events
Content-Type: application/json

{
  "name": "Circus",
  "description": "Kids circus",
  "author": "Andrii",
  "place": "Bremen, CircusHof, 11",
  "quantityOfMembers": "250",
  "photo": "added photo #2",
  "date": "01/09/2023"

}

### Add event №3

POST http://localhost:8080/api/events
Content-Type: application/json

{
  "name": "Karaoke",
  "description": "Singing Song",
  "author": "Joseph",
  "place": "Amsterdam, Sing allee, 5",
  "quantityOfMembers": "12",
  "photo": "added photo.png",
  "date": "02/04/2022"

}

### Add event №4

POST http://localhost:8080/api/events
Content-Type: application/json

{
  "name": "Beach Party",
  "description": "Dancing",
  "author": "Barbara Roth",
  "place": "Gdansk beach",
  "quantityOfMembers": "120",
  "photo": "added photo.png",
  "date": "03/08/2023"

}

### Get all events

GET localhost:8080/api/events


### Delete Event

DELETE localhost:8080/api/events/100

### Update event №1

PUT localhost:8080/api/events/1
Content-Type: application/json

{
  "newStatus" : "ENDED"
}


### Get paginated event

GET localhost:8080/api/events/paginated?page=0&size=2